"""add_rule_versions

Revision ID: 10dd2dcf16f5
Revises: c7f8d3e2a1b9
Create Date: 2026-06-03 06:09:10.402382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10dd2dcf16f5'
down_revision: Union[str, Sequence[str], None] = 'c7f8d3e2a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'file_type',
               existing_type=postgresql.ENUM('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype'),
               type_=sa.Enum('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'OTHER'::filetype"))
    op.alter_column('files', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', name='filestatus'),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', 'NEEDS_REVIEW', name='filestatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::filestatus"))
    op.drop_index(op.f('idx_files_file_type'), table_name='files')
    op.drop_index(op.f('idx_files_status'), table_name='files')
    op.drop_index(op.f('idx_files_uploaded_at'), table_name='files')
    op.drop_index(op.f('idx_files_uploaded_by'), table_name='files')
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_uploaded_at'), 'files', ['uploaded_at'], unique=False)
    op.drop_constraint(op.f('files_uploaded_by_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['uploaded_by'], ['id'])
    op.drop_index(op.f('idx_notes_author_id'), table_name='notes')
    op.drop_index(op.f('idx_notes_file_id'), table_name='notes')
    op.create_index(op.f('ix_notes_file_id'), 'notes', ['file_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_constraint(op.f('notes_author_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('notes_file_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'files', ['file_id'], ['id'])
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype'),
               type_=sa.Enum('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'INFO'::notificationtype"))
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::taskstatus"))
    op.drop_index(op.f('idx_tasks_celery_task_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_file_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_constraint(op.f('tasks_file_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'files', ['file_id'], ['id'])
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_sso_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=False)
    
    # Explicitly create rule_versions table
    op.create_table(
        'rule_versions',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('rule_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('rule_name', sa.String(), nullable=False),
        sa.Column('rule_type', sa.Enum('keyword', 'regex', 'llm_prompt', 'plugin', 'logic_graph', name='ruletype'), nullable=False),
        sa.Column('rule_content', sa.Text(), nullable=False),
        sa.Column('severity', sa.Enum('warning', 'fail', 'reference', name='severity'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('logic_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['verification_rules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Explicitly drop rule_versions table
    op.drop_table('rule_versions')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_file_id_fkey'), 'tasks', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_file_id'), 'tasks', ['file_id'], unique=False)
    op.create_index(op.f('idx_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::taskstatus"))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype', native_enum=False),
               type_=postgresql.ENUM('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype'),
               existing_nullable=True,
               existing_server_default=sa.text("'INFO'::notificationtype"))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_file_id_fkey'), 'notes', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notes_author_id_fkey'), 'notes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_file_id'), table_name='notes')
    op.create_index(op.f('idx_notes_file_id'), 'notes', ['file_id'], unique=False)
    op.create_index(op.f('idx_notes_author_id'), 'notes', ['author_id'], unique=False)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_uploaded_by_fkey'), 'files', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_files_uploaded_at'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.create_index(op.f('idx_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_files_uploaded_at'), 'files', ['uploaded_at'], unique=False)
    op.create_index(op.f('idx_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('idx_files_file_type'), 'files', ['file_type'], unique=False)
    op.alter_column('files', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', 'NEEDS_REVIEW', name='filestatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', name='filestatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::filestatus"))
    op.alter_column('files', 'file_type',
               existing_type=sa.Enum('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype', native_enum=False),
               type_=postgresql.ENUM('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype'),
               existing_nullable=True,
               existing_server_default=sa.text("'OTHER'::filetype"))
    # ### end Alembic commands ###
