"""Add dynamic rule tables

Revision ID: 156287492b65
Revises: 455ad299810f
Create Date: 2026-05-24 10:46:24.079486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156287492b65'
down_revision: Union[str, Sequence[str], None] = '455ad299810f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('files', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', name='filestatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_files_file_type'), table_name='files')
    op.drop_index(op.f('idx_files_status'), table_name='files')
    op.drop_index(op.f('idx_files_uploaded_at'), table_name='files')
    op.drop_index(op.f('idx_files_uploaded_by'), table_name='files')
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_uploaded_at'), 'files', ['uploaded_at'], unique=False)
    op.drop_constraint(op.f('files_uploaded_by_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['uploaded_by'], ['id'])
    op.drop_index(op.f('idx_notes_author_id'), table_name='notes')
    op.drop_index(op.f('idx_notes_file_id'), table_name='notes')
    op.create_index(op.f('ix_notes_file_id'), 'notes', ['file_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_constraint(op.f('notes_file_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('notes_author_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'files', ['file_id'], ['id'])
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_tasks_celery_task_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_file_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_constraint(op.f('tasks_file_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'files', ['file_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_sso_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_sso_id'), 'users', ['sso_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_file_id_fkey'), 'tasks', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_file_id'), 'tasks', ['file_id'], unique=False)
    op.create_index(op.f('idx_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('SUCCESS', 'ERROR', 'WARNING', 'INFO', name='notificationtype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_author_id_fkey'), 'notes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notes_file_id_fkey'), 'notes', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_file_id'), table_name='notes')
    op.create_index(op.f('idx_notes_file_id'), 'notes', ['file_id'], unique=False)
    op.create_index(op.f('idx_notes_author_id'), 'notes', ['author_id'], unique=False)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_uploaded_by_fkey'), 'files', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_files_uploaded_at'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.create_index(op.f('idx_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_files_uploaded_at'), 'files', ['uploaded_at'], unique=False)
    op.create_index(op.f('idx_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('idx_files_file_type'), 'files', ['file_type'], unique=False)
    op.alter_column('files', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WARNING', name='filestatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('files', 'file_type',
               existing_type=sa.Enum('PRODUCTION_PLAN', 'QUALITY_REPORT', 'PURCHASE_ORDER', 'SUPPLIER_QUALIFICATION', 'PRODUCT_SPECIFICATION', 'OTHER', name='filetype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'other'::character varying"))
    # ### end Alembic commands ###
