"""Add logic_config and NEEDS_REVIEW status

Revision ID: a9bf6820e18c
Revises: 156287492b65
Create Date: 2026-05-24 11:40:19.223311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9bf6820e18c'
down_revision: Union[str, Sequence[str], None] = '156287492b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_rules', sa.Column('logic_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_rules', 'logic_config')
    # ### end Alembic commands ###
